apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 31433
    protocol: TCP
    name: mssql
  selector:
    app: mssql
