apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  labels:
    app: mssql
type: Opaque
data:
  # SA_PASSWORD: YourStr0ngP@ssw0rd!
  # echo -n 'YourStr0ngP@ssw0rd!' | base64
  SA_PASSWORD: WW91clN0cjBuZ1BAc3N3MHJkIQ==
