apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # postgres / admin123
  # Encodé en base64 : echo -n 'postgres' | base64
  POSTGRES_USER: cG9zdGdyZXM=
  # Encodé en base64 : echo -n 'admin123' | base64
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  # Encodé en base64 : echo -n 'demo' | base64
  POSTGRES_DB: ZGVtbw==
